### ISSUE TITLE
Write component that returns the last changed commit sha for each file

### ISSUE THREAD

**Issue by rcannood** [openproblems-bio/openproblems-v2#30]
The interface of the component could be something like below. Implementaton of the `--show_history` is optional for now.

```yaml
functionality:
  name: list_git_shas
  namespace: common
  arguments:
    - name: --input
      type: file
      description: Path to a git repository
      required: true
      example: /path/to/repo
    - name: --output
      type: file
      description: |
        A json containing a list of entries. Each entry must have the
        following values: 
  
        * "path" `string`: Path a file in the repository
        * "last_modified" `string`: Date of then the file was last modified, in `yyyy-mm-dd HH:mm:ss` format.
        * "sha" `string`: Sha of the commit in which the file was last modified
        * "history_sha" `string` (optional): A list of SHAs during which the file was modified
      required: true
      example: output.json
    - name: --show_history
      type: boolean_true
      description: Whether or not to include the full history of SHAs for each file.
```
