### ISSUE TITLE
Rename terminology

### ISSUE THREAD

**Issue by KaiWaldrant** [openproblems-bio/openproblems-v2#93]
- [x] Rename `create_skeleton` to `create_component`.
- [x] #100
- [x] Remove `common/dataset_concatenate`
- [x] Rename `src/<task>/split_dataset` to `src/<task>/datasets/process_dataset` (or `.../process_common_dataset`?)
- [x] Update **method info** sections of all tasks to:

```yaml
info:
    pretty_name: Foopy
    summary: 'FILL IN: A one sentence summary of this method.'
    description: 'FILL IN: A (multiline) description of how this method works.'
    reference: bibtex_reference_key
    documentation_url: https://url.to/the/documentation
    repository_url: https://github.com/organisation/repository
    preferred_normalization: log_cpm
```

- [x] Update **metric info** sections of all tasks to:

```yaml
      - name: foopy
        pretty_name: Foopy
        summary: 'FILL IN: A one sentence summary of this metric.'
        description: 'FILL IN: A (multiline) description of how this metric works.'
        reference: bibtex_reference_key
        documentation_url: https://url.to/the/documentation
        repository_url: https://github.com/organisation/repository
        min: 0
        max: 1
        maximize: 'true'
```

- [x] Update `get_method_info` and `get_metric_info` scripts to convert new names to those in v1

- [x] #106
